// Palavras
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const SUBMIT_WORD = 'SUBMIT_WORD';
export const INCREMENT_CURRENT_WORD = 'UPDATE_CURRENT_WORD';
export const DECREMENT_CURRENT_WORD = 'DECREMENT_CURRENT_WORD';