//@ts-nocheck
import React, { useEffect } from 'react';
import Head from 'next/head';

import Header from '../components/header';
import Keyboard from '../components/keyboard';
import Game from '../components/game';
import { useDispatch, useSelector } from 'react-redux';
import { updateGameStatus } from '../store/actions/game';
import Finish from '../components/finish';

export default function Home() {
  const dispatch = useDispatch();

  const { finish } = useSelector((state) => state.game);

  useEffect(() => {  
    var lettrex = localStorage.getItem('lettrex');
    lettrex = lettrex ? JSON.parse(lettrex) : {};
    
    dispatch(updateGameStatus(lettrex));
  }, []);

  return (
    <>
      <Head>
        <title>Lettrex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', alignItems: 'center' }}>
        <Header />
        <Game />
        { !finish ? <Keyboard /> : <Finish /> }       
      </div>
    </>
  );
}

